name: Build and update IGVF clients

on:
  workflow_dispatch:
jobs:
  build-and-update-clients:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.IGVF_CLIENT_BUILDER_APP_ID }}
          private-key: ${{ secrets.IGVF_CLIENT_BUILDER_PRIVATE_KEY }}
          owner: "IGVF-DACC"
          repositories: "igvf-client-openapi-spec,igvf-python-client,igvf-async-python-client,igvf-r-client"
      - name: Clone remote repo
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          echo hello >> abc.txt
          echo ${GITHUB_TOKEN} >> abc.txt
          cat abc.txt
#          git clone https://$GITHUB_TOKEN@github.com/IGVF-DACC/igvf-client-openapi-spec.git
#          ls
#          ls igvf-python-client/
